name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
          SLUG: 211j-countdown-timer-woocommerce
